### ISSUE TITLE
Scripting language

### ISSUE THREAD

**Issue by marcobambini** [untoldengine/UntoldEngine#112]
If you need a scripting language I'd be more than happy to help you integrate Gravity https://github.com/marcobambini/gravity

**Comment by untoldengine** [comment]
Hi @marcobambini 

Sorry for the late reply, been very busy lately.

Let me look into Gravity this week and see if it is a good idea to integrate it.

Thanks

Harold

**Comment by untoldengine** [comment]
Hi @marcobambini,

I'm evaluating several scripting languages to integrate into my game engine. Your Gravity language seems very cool. Do you have more documentation/examples on how to embed Gravity? For example, how to call a C++ function from a Gravity script and vice-versa.

**Comment by marcobambini** [comment]
Hi @untoldengine,

Please take a look at https://github.com/marcobambini/gravity/tree/master/examples/GravityCpp
