### ISSUE TITLE
Source files seem to be missing from the repository

### ISSUE THREAD

**Issue by Lancelotbronner** [untoldengine/UntoldEngine#639]
All the Metal shaders are missing from the source tree, is that intentional?

It seems like additional resources (for the demo and starter game) are also missing.

**Comment by untoldengine** [comment]
The shaders source code have not been included yet. I need to clean them up before I push them. However, the metallib is included.

Are you able to run the engine? I just checked and the resources for the demo and starter game are there. They are inside Sources/UntoldEngine/Resources

**Comment by Lancelotbronner** [comment]
I got it to run but it needed some tweaking of `Package.swift`. I'll wait for the shader code since that's what I wanted to see!
